version: '3.8'
services:

  lanchonete-cliente-app:
    build: .
    container_name: lanchonete-app-cliente
    image: gtbarbosa/fiap-tech-challenge-lanchonete-api-cliente:latest
    ports:
      - 8282:8282
    networks:
      - lanchonete-network
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:6.0
    container_name: mongo-cliente-lanchonete-db
    ports:
      - 27017:27017
    networks:
      - lanchonete-network
    environment:
      MONGO_INITDB_DATABASE: cliente
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass

networks:
  lanchonete-network:
