apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-lanchonete-app-cliente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-lanchonete-app-cliente
  template:
    metadata:
      labels:
        app: pod-lanchonete-app-cliente
    spec:
      containers:
        - name: container-lanchonete-app-cliente
          image: gtbarbosa/fiap-tech-challenge-lanchonete-cliente
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap-cliente
                  key: APP_NAME
            - name: SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: app-configmap-cliente
                  key: SHOW_SQL
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: app-configmap-cliente
                  key: MONGODB_URI
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap-cliente
                  key: APP_PORT
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "700m"
              memory: "768Mi"