apiVersion: v1
kind: Service
metadata:
  name: svc-lanchonete-app-cliente
  labels:
    app: svc-lanchonete-app-cliente
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: pod-lanchonete-app-cliente