spring:
  application:
    name: ${APP_NAME:lanchonete}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://user:pass@mongo-db:27017/cliente?authSource=admin}
    jpa:
      show-sql: ${SHOW_SQL:true}

server:
  port: ${APP_PORT:8282}
