apiVersion: v1
kind: Pod
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  containers:
    - name: mongodb
      image: mongo:6.0
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGO_INITDB_DATABASE
          value: cliente
      ports:
        - containerPort: 27017
