name: Deploy no Cluster EKS

on:
  workflow_run:
    workflows:
      - Cria o PR para a main
    types:
      - completed

jobs:
  approve-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Esperar Aprovação
        uses: askuia/github-actions-approval@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          approval_message: "Aprovar o deploy no cluster EKS"
          timeout: 30m # Tempo limite para aprovação (30 minutos)

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy application to EKS
        run: |
          kubectl apply -f kubernetes --recursive # Substitua pelo caminho dos manifestos do Kubernetes
